name: Build report

on:
  push:
    branches: [report/*]
  pull_request:
    branches: [report/*]
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: report/build/main.tex
          latexmk_use_xelatex: true
      - name: Push to repository
        run: |
          git commit -m "Automated report build"
          git push
    
